# netlify.toml
[build]
  # 1. Base Directory Fix: Tells Netlify/Vite the project root is NOT the repo root.
  # Vite uses 'index.html' as its entry point, and it looks for it based on the 'base' config.
  # Since index.html is in 'public' (where Vite normally expects it), but we need to tell 
  # Netlify that Vite's files are relative to the root, we set the build command explicitly.
  
  # Set the command to run the build process from the root, but ensure the publish directory is correct.
  command = "npm run build"
  
  # Set the publish directory to the standard output directory created by Vite
  publish = "dist"

# Add a redirect rule for Firebase Hosting compatibility (optional but recommended)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
