# netlify.toml

[build]
  # Build command (runs vite build)
  command = "npm run build"
  
  # Directory where Vite outputs static files
  publish = "dist"

# CRITICAL FIX: Overrides Netlify's default 'netlify/functions' directory.
# This prevents Netlify from building its own functions, allowing the Firebase functions setup to work.
[functions]
  directory = "netlify-ignore"

# Essential for Firebase/React routing (redirects all traffic to the single-page application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
